import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

const PROVIDERS = [
    { id: 'safehaven', name: 'Safe Haven', description: 'Safe Haven checkout, temporary bank-account funding and Safe Haven bank payouts.' },
    { id: 'paystack', name: 'Paystack', description: 'Paystack hosted checkout for funding and purchases, plus Paystack Transfers for bank payouts.' },
] as const;

export default function Edit({ activeProvider, configuredProviders }: { activeProvider: string; configuredProviders: Record<string, boolean> }) {
    const { data, setData, patch, processing, errors } = useForm({ active_provider: activeProvider });
    const submit = (event: FormEvent) => { event.preventDefault(); patch(route('admin.payment-provider.update')); };
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Payment routing</h2>}><Head title="Payment routing" /><div className="mx-auto max-w-4xl p-5 sm:p-8"><form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-card ring-1 ring-gray-900/5"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-950">Active payment provider</h1><p className="mt-2 text-sm leading-6 text-gray-500">This switch applies immediately to new wallet funding requests, direct utility checkout and wallet-to-bank withdrawals. Existing pending payments continue with the provider that created them.</p></div><div className="grid gap-4 sm:grid-cols-2">{PROVIDERS.map(provider => { const ready = configuredProviders[provider.id]; return <label key={provider.id} className={`rounded-2xl border-2 p-5 transition ${ready ? 'cursor-pointer' : 'cursor-not-allowed opacity-60'} ${data.active_provider === provider.id ? 'border-brand-700 bg-brand-50' : 'border-gray-100 hover:border-brand-200'}`}><div className="flex items-start gap-3"><input disabled={!ready} type="radio" name="provider" value={provider.id} checked={data.active_provider === provider.id} onChange={() => setData('active_provider', provider.id)} className="mt-1 text-brand-700 focus:ring-brand-600"/><div><div className="font-bold text-gray-900">{provider.name}</div><p className="mt-2 text-sm leading-6 text-gray-500">{provider.description}</p><span className={`mt-3 inline-flex rounded-full px-3 py-1 text-xs font-semibold ${ready ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-800'}`}>{ready ? 'Credentials ready' : 'Configuration required'}</span>{activeProvider === provider.id && <span className="ml-2 mt-3 inline-flex rounded-full bg-brand-100 px-3 py-1 text-xs font-semibold text-brand-700">Currently active</span>}</div></div></label>})}</div>{errors.active_provider && <p className="mt-4 text-sm font-medium text-red-600">{errors.active_provider}</p>}<div className="mt-6 rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>Before switching:</strong> confirm that the selected provider's API credentials, webhook URL and payout balance are ready. JolaxPay never changes provider for a payment already in progress.</div><button disabled={processing || data.active_provider === activeProvider || !configuredProviders[data.active_provider]} className="mt-6 rounded-xl bg-brand-700 px-6 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{processing ? 'Switching…' : 'Save payment provider'}</button></form></div></AuthenticatedLayout>;
}
